---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-a-username
  name: get-a-username
  namespace: {{ .Values.usertoolNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: get-a-username
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: get-a-username
    spec:
      containers:
      - name: get-a-username
        env:
        - name: LAB_ADMIN_PASS
          value: {{ .Values.labAdminPassword }}
        - name: LAB_DURATION_HOURS
          value: {{ .Values.labDuration }}
        - name: LAB_EXTRA_URLS
          value: {{ .Values.labExtraUrls }}
        - name: LAB_MODULE_URLS
          value: {{ .Values.labModuleUrls }}
        - name: LAB_REDIS_HOST
          value: redis
        - name: LAB_REDIS_PASS
          value: redis
        - name: LAB_TITLE
          value: "Lab Guides"
        - name: LAB_USER_ACCESS_TOKEN
          value: {{ .Values.labAccessToken }}
        - name: LAB_USER_COUNT
          value: "{{ .Values.labUserCount }}"
        - name: LAB_USER_PAD_ZERO
          value: "false"
        - name: LAB_USER_PASS
          value: {{ .Values.labUserPassword }}
        - name: LAB_USER_PREFIX
          value: {{ .Values.labUserPrefix }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
