---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: {{ .Values.usertoolNamespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.pvc }}
