---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  name: redis
  namespace: {{ .Values.usertoolNamespace }}
stringData:
  database-password: redis
